// Shared NCISM designation reference data — single source of truth for every
// designation's label/category/level/duty-description. Originally lived only
// inside admin.js's HR ladder; extracted so navbar.js can show a staff member
// their own duty description on any page, without a second drifting copy.
export const DESIGS = [
  {v:'principal',                   l:'Principal',                       cat:'Administration', lv:1, d:'Academic + administrative head of the college — overall NCISM compliance, faculty recruitment, exam liaison.'},
  {v:'vice_principal',              l:'Vice Principal',                  cat:'Administration', lv:2, d:'Deputises for the Principal; coordinates academic schedules and discipline.'},
  {v:'cmo',                         l:'Chief Medical Officer',           cat:'Administration', lv:1, d:'Senior-most clinical authority — owns treatment protocols and clinical governance hospital-wide.'},
  {v:'medical_director',            l:'Medical Director (Dean/Principal/Director)', cat:'Administration', lv:0, d:'Apex administrative + clinical head of the institution (Sch XX/1) — final authority on hospital operations.'},
  {v:'medical_superintendent',      l:'Medical Superintendent',          cat:'Administration', lv:2, d:'Runs day-to-day hospital operations — duty rosters, bed management, discipline (Sch XX/2).'},
  {v:'deputy_medical_superintendent',l:'Deputy Medical Superintendent',  cat:'Administration', lv:3, d:'Assists the Medical Superintendent; covers IPD/OPD operational oversight (Sch XX/3).'},
  {v:'administrative_officer',      l:'Administrative Officer',          cat:'Administration', lv:4, d:'Non-clinical administration — HR records, procurement paperwork, statutory filings (Sch XX/4).'},
  {v:'opd_incharge',                l:'Office Superintendent',           cat:'Administration', lv:3, d:'Administers hospital office/OPD administrative staff — registration desks, clerical operations and daily patient flow (Sch XX/9).'},
  {v:'hod',                         l:'Head of Department (HOD)',        cat:'Faculty',        lv:1, d:'Senior-most faculty in a clinical department — teaching, patient care and NCISM compliance for that dept (Sch I).'},
  {v:'professor',                   l:'Professor',                       cat:'Faculty',        lv:2, d:'Senior teaching faculty — UG/PG teaching, OPD/IPD supervision, PG guide eligibility (Sch I).'},
  {v:'associate_professor',         l:'Associate Professor',             cat:'Faculty',        lv:3, d:'Mid-senior teaching faculty supporting the Professor/HOD in teaching and clinical duties (Sch I).'},
  {v:'assistant_professor',         l:'Assistant Professor',             cat:'Faculty',        lv:4, d:'Junior teaching faculty — UG teaching + OPD/IPD clinical duties (Sch I).'},
  {v:'senior_resident',             l:'Senior Resident',                 cat:'Faculty',        lv:5, d:'PG-qualified resident supervising junior residents/interns and running OPD/IPD care (Sch I, PG depts only).'},
  {v:'junior_resident',             l:'Junior Resident',                 cat:'Faculty',        lv:6, d:'House Officer / Clinical Registrar — first point of clinical contact under faculty supervision (Sch XX/41).'},
  {v:'medical_officer',             l:'Medical Officer',                 cat:'Clinical',       lv:5, d:'BAMS-qualified doctor providing direct patient care across OPD/IPD.'},
  {v:'resident_medical_officer',    l:'Resident Medical Officer (RMO)',  cat:'Clinical',       lv:6, d:'24×7 in-house duty doctor — first responder for IPD emergencies and Medical In-Patients ward rounds (Sch XX/6, XX/34).'},
  {v:'emergency_medical_officer',   l:'Emergency Medical Officer (EMO)', cat:'Clinical',       lv:6, d:'Staffs the Emergency/Casualty desk round the clock (Sch XX/6, XX/34, XX/37).'},
  {v:'general_duty_medical_officer',l:'General Duty Medical Officer (GDMO)',cat:'Clinical',    lv:7, d:'Ward-duty doctor for Medical/Surgical IPD rounds (Sch XX/34, XX/37).'},
  {v:'resident_surgical_officer',   l:'Resident Surgical Officer (RSO)', cat:'Clinical',       lv:6, d:'24×7 in-house duty doctor for the Surgical In-Patients ward (Sch XX/37).'},
  {v:'pg_scholar',                  l:'PG Scholar',                      cat:'Academic',       lv:7, d:'Postgraduate student under a recognised PG guide — thesis + clinical training rotation.'},
  {v:'intern',                      l:'Intern',                          cat:'Academic',       lv:8, d:'Compulsory rotatory internship — supervised patient care across all clinical departments.'},
  {v:'nursing_superintendent',      l:'Nursing Superintendent',          cat:'Nursing',        lv:1, d:'Matron — heads the entire nursing service, duty rosters, nursing standards (Sch XX/7).'},
  {v:'deputy_nursing_superintendent',l:'Deputy Nursing Superintendent',  cat:'Nursing',        lv:2, d:'Assistant Matron — supports the Nursing Superintendent across shifts/wards (Sch XX/8).'},
  {v:'ward_sister',                 l:'Ward Sister / Sr. Staff Nurse',   cat:'Nursing',        lv:3, d:'Senior nurse in charge of a ward/shift — supervises staff nurses and patient care.'},
  {v:'staff_nurse',                 l:'Staff Nurse',                     cat:'Nursing',        lv:4, d:'Bedside nursing care across OPD/IPD/PK/OT/Labour Room (Sch XX/20 and others).'},
  {v:'nursing_intern',              l:'Nursing Intern',                  cat:'Nursing',        lv:5, d:'Nursing student under supervised clinical rotation.'},
  {v:'chief_pharmacist',            l:'Chief Pharmacist',                cat:'Pharmacy',       lv:1, d:'Dispensary In-charge — owns stock, dispensing accuracy and pharmacy compliance (Sch XX/23).'},
  {v:'pharmacist',                  l:'Pharmacist',                      cat:'Pharmacy',       lv:2, d:'Ayurveda-qualified pharmacist dispensing prescriptions (Sch XX/22).'},
  {v:'pharmacy_assistant',          l:'Pharmacy Assistant',              cat:'Pharmacy',       lv:3, d:'Assists the pharmacist with stock handling, billing and dispensing.'},
  {v:'pk_incharge',                 l:'Panchakarma In-charge',           cat:'Therapy',        lv:1, d:'Heads the Panchakarma therapy section — protocol adherence and therapist rostering (Sch XX/40).'},
  {v:'panchakarma_cook',            l:'Panchakarma Preparation-Room Cook', cat:'Therapy',      lv:4, d:'Prepares medicated oils, ghees and decoctions used in Panchakarma therapy (Sch XX/39, optional) — distinct from the Pathya-Diet kitchen.'},
  {v:'senior_therapist',            l:'Senior Therapist',                cat:'Therapy',        lv:2, d:'Experienced therapist leading complex Panchakarma/Kriyakalpa procedures (Sch XX/40, XX/48).'},
  {v:'therapist',                   l:'Therapist',                       cat:'Therapy',        lv:3, d:'Delivers Panchakarma, Kriyakalpa or Physiotherapy procedures under supervision (Sch XX/40, 48, 49).'},
  {v:'therapy_assistant',           l:'Therapy Assistant / Attender',    cat:'Therapy',        lv:4, d:'Supports therapists with procedure setup, patient positioning and cleanup.'},
  {v:'receptionist',                l:'Receptionist',                    cat:'Admin Staff',    lv:1, d:'Front-desk registration and telephone enquiries (Sch XX/16).'},
  {v:'registration_clerk',          l:'Registration Clerk',              cat:'Admin Staff',    lv:2, d:'Patient registration and record entry at the OPD desk (Sch XX/17).'},
  {v:'billing_clerk',               l:'Billing Clerk',                   cat:'Admin Staff',    lv:2, d:'Generates and collects OPD/IPD/pharmacy bills (Sch XX/17).'},
  {v:'medical_record_officer',      l:'Medical Record Officer',          cat:'Admin Staff',    lv:2, d:'Owns the Medical Records Department — filing, retrieval, MLC register upkeep (Sch XX/18).'},
  {v:'medical_record_technician',   l:'Medical Record Technician',       cat:'Admin Staff',    lv:3, d:'Maintains and retrieves patient case records (Sch XX/18).'},
  {v:'public_relations_officer',    l:'Public Relations Officer',        cat:'Admin Staff',    lv:3, d:'Handles patient grievances, feedback and external communications.'},
  {v:'finance_manager',             l:'Finance Manager / Accounts Officer', cat:'Admin Staff',  lv:1, d:'Heads the finance department under the Administrator — owns billing, payroll and insurance claims oversight; Clerks/Accounts Staff and Store Keepers work under this position (Sch XX/10, XX/11).'},
  {v:'accountant',                  l:'Accountant',                      cat:'Admin Staff',    lv:2, d:'Books, reconciles and reports hospital finances — billing, payroll, insurance claims (Sch XX/10, XX/11).'},
  {v:'store_keeper',                l:'Store Keeper (Main / Pharmacy Store)', cat:'Admin Staff', lv:3, d:'Manages stock receipt, storage and issue for the main or pharmacy store, under the Finance Manager.'},
  {v:'lab_incharge',                l:'Lab In-charge',                   cat:'Diagnostics',    lv:1, d:'Heads the pathology lab — quality control, staffing, report sign-off.'},
  {v:'roganidana_pg',               l:'PG Roganidana (Report Signatory)', cat:'Diagnostics',   lv:1, d:'PG-qualified Roganidana faculty who signs off Ayurvedic diagnostic interpretations.'},
  {v:'pathologist',                 l:'Pathologist (Part-time)',          cat:'Diagnostics',    lv:1, d:'Part-time specialist validating pathology reports.'},
  {v:'radiologist',                 l:'Radiologist (Part-time)',          cat:'Diagnostics',    lv:1, d:'Part-time specialist reporting X-ray/USG/imaging studies.'},
  {v:'sonologist',                  l:'Sonologist (Part-time)',           cat:'Diagnostics',    lv:1, d:'Part-time specialist performing/reporting ultrasound studies (PCPNDT registered).'},
  {v:'microbiologist',              l:'Microbiologist (Part-time)',       cat:'Diagnostics',    lv:1, d:'Part-time specialist overseeing culture/sensitivity and infection-control testing (Sch XX/30).'},
  {v:'lab_technician',              l:'Lab Technician',                   cat:'Diagnostics',    lv:2, d:'DMLT-qualified — sample collection, processing and routine test performance (Sch XX/24).'},
  {v:'radiographer',                l:'Radiographer / X-ray Technician',  cat:'Diagnostics',    lv:2, d:'Operates X-ray/imaging equipment and AERB safety logs (Sch XX/26).'},
  {v:'lab_attendant',               l:'Lab Attendant',                    cat:'Diagnostics',    lv:3, d:'Assists lab technicians — specimen handling and housekeeping of the lab (Sch XX/25).'},
  {v:'dark_room_assistant',         l:'Dark Room Assistant',              cat:'Diagnostics',    lv:3, d:'Develops X-ray film in the dark room — only needed if using non-digital X-ray equipment (Sch XX/27, optional).'},
  {v:'ot_technician',               l:'OT Technician / Surgical Tech',   cat:'Clinical',       lv:7, d:'Assists surgeons — instrument prep, sterile technique, OT equipment upkeep (Sch XX/43).'},
  {v:'ophthalmic_technician',       l:'Ophthalmic Technician',           cat:'Clinical',       lv:7, d:'Assists Shalakya-Netra faculty with eye examinations and minor procedures.'},
  {v:'ent_technician',              l:'ENT Technician / Audiologist',    cat:'Clinical',       lv:7, d:'Assists Shalakya-KNM faculty with ENT examinations, audiometry and minor procedures.'},
  {v:'anm',                         l:'Auxiliary Nurse Midwife (ANM)',    cat:'Nursing',        lv:4, d:'Assists nursing staff in wards and the Labour Room, ayah-level duties (Sch XX/33, XX/36).'},
  {v:'yoga_instructor',             l:'Yoga Instructor',                 cat:'Wellness',       lv:2, d:'Conducts yoga therapy sessions under the Swasthavritta department (Sch XX/51).'},
  {v:'dietitian',                   l:'Dietitian / Nutritionist',        cat:'Wellness',       lv:2, d:'Plans Pathya-Apathya diet charts for OPD/IPD patients (Sch XX/52).'},
  {v:'wellness_counsellor',         l:'Wellness Counsellor',             cat:'Wellness',       lv:3, d:'Provides lifestyle and preventive-health counselling under Swasthavritta.'},
  {v:'clinical_psychologist',       l:'Clinical Psychologist / Counsellor', cat:'Wellness',    lv:2, d:'Provides psychological assessment and counselling support (Manasaroga referrals).'},
  {v:'cssd_incharge',               l:'CSSD In-charge / Sterilisation Supervisor', cat:'Clinical',   lv:6, d:'Owns central sterilisation protocols and instrument-tracking logs (Sch XX/CS1).'},
  {v:'cssd_technician',             l:'CSSD Technician / Sterilisation Tech',     cat:'Clinical',    lv:7, d:'Operates autoclaves and sterilisation equipment (Sch XX/CS1).'},
  // Session 134: split out of the generic attender/cssd_technician designations, which had
  // been silently double-counting the same staff against two Schedule XX rows each (an
  // attender satisfied both OT Attendants AND CSSD/Sterilisation Aya; a cssd_technician
  // satisfied both Anushastra Karma Technician AND CSSD/Sterilisation Staff) since there was
  // no way to tell which specific post a given staff member actually held.
  {v:'ot_attendant',                l:'OT Attendant',                    cat:'Support',        lv:3, d:'Ward-helper duties specific to the Operation Theatre — patient shifting, instrument runs (Sch XX/44).'},
  {v:'anushastra_technician',       l:'Anushastra Karma Technician',      cat:'Clinical',       lv:7, d:'Assists Shalya Tantra faculty with Agnikarma/Raktamokshana/Ksharakarma procedures (Sch XX/45).'},
  {v:'cssd_aya',                    l:'CSSD / Sterilisation Aya',        cat:'Support',        lv:3, d:'Ward-helper duties specific to the central sterilisation unit — pack handling, area upkeep (Sch XX/CS2).'},
  {v:'maintenance_engineer',        l:'Maintenance Engineer',            cat:'Support',        lv:1, d:'Maintains biomedical equipment, electrical and civil infrastructure.'},
  {v:'maintenance_supervisor',      l:'Maintenance Supervisor',          cat:'Support',        lv:2, d:'Supervises day-to-day maintenance staff and complaint resolution.'},
  {v:'bmw_officer',                 l:'Biomedical Waste Officer',        cat:'Support',        lv:1, d:'Owns BMW segregation, CBWTF pickup logs and SPCB compliance reporting.'},
  {v:'palha_diet_incharge',         l:'Palha-diet In-charge',            cat:'Wellness',       lv:1, d:'Heads the Pathya-Diet kitchen — Ayurvedic diet planning and indent fulfilment (Sch XX/52).'},
  {v:'diet_cook',                   l:'Ayurvedic Diet Cook',             cat:'Wellness',       lv:3, d:'Prepares Pathya-Apathya meals per the diet chart (Sch XX/53).'},
  {v:'security_supervisor',         l:'Security Supervisor',             cat:'Support',        lv:1, d:'Oversees hospital security staff, access control and incident logs.'},
  {v:'security_guard',              l:'Security Guard',                  cat:'Support',        lv:2, d:'Staffs entry points and wards for round-the-clock physical security.'},
  {v:'sanitation_supervisor',       l:'Sanitation Supervisor',           cat:'Support',        lv:1, d:'Oversees housekeeping staff and hospital cleanliness/infection-control rounds.'},
  {v:'sanitation_worker',           l:'Sanitation Worker',               cat:'Support',        lv:2, d:'Performs ward, OPD and common-area housekeeping.'},
  {v:'laundry_supervisor',          l:'Laundry Supervisor',              cat:'Support',        lv:1, d:'Oversees linen collection, washing cycles and BMW-compliant handling of soiled linen.'},
  {v:'laundry_worker',              l:'Laundry Worker',                  cat:'Support',        lv:2, d:'Washes, dries and distributes hospital linen across wards and OT.'},
  {v:'driver',                      l:'Driver / Ambulance Driver',       cat:'Support',        lv:2, d:'Drives the ambulance/hospital vehicles, on-call for patient transport.'},
  {v:'attender',                    l:'Attender / Helper',               cat:'Support',        lv:3, d:'General ward/admin helper duties — patient shifting, errands (Sch XX/12, 33, 36).'},
];
export const DESIG_MAP = Object.fromEntries(DESIGS.map(d=>[d.v,d]));
export const DESIG_CATS = [...new Set(DESIGS.map(d=>d.cat))];

// Fallback duty text keyed by plain ROLE (not designation) — shown when a
// staff member's profile has no designation set at all (older/simpler
// tenants that don't use the full NCISM ladder). Deliberately short and
// role-level, not Schedule-XX legal register, since there's no specific
// designation to quote a schedule reference against.
export const ROLE_DUTY_FALLBACK = {
  super_admin:     'Full administrative control of this organisation’s AyurXpert account — staffing, departments, subscription and compliance settings.',
  dept_admin:      'Administrative control of this organisation’s day-to-day operations — staffing, departments and OPD/IPD setup.',
  doctor:          'Clinical consultation, diagnosis and treatment of patients across OPD/IPD, prescription authoring and lab/imaging ordering.',
  trainee_doctor:  'PG/Intern clinical training — drafts consultations and orders under a supervising doctor’s review and final sign-off.',
  receptionist:    'Front-desk patient registration, appointment queueing and bill collection.',
  pharmacist:      'Prescription dispensing, stock management and pharmacy billing.',
  nurse:           'Bedside nursing care — vitals, medication administration, IPD charting and shift handover.',
  nurse_manager:   'Nursing service oversight — duty rostering, nursing-scoped leave approval and compliance monitoring.',
  lab_tech:        'Sample collection, diagnostic testing and lab/imaging report entry.',
  accountant:      'Hospital billing, payroll and insurance-claims bookkeeping.',
  cashier:         'Revenue collection and insurance-cycle billing at the counter.',
  finance_manager: 'Oversight of hospital finance — billing, payroll, insurance claims and expense audits.',
  therapist:       'Delivery of Panchakarma/Kriyakalpa/Physiotherapy procedures under clinical supervision.',
  student:         'Academic training placement — no independent clinical or administrative duties yet.',
  diet_staff:      'Ayurvedic Pathya-Apathya diet planning and kitchen indent fulfilment.',
  mrd_staff:       'Medical records filing, retrieval and MLC register upkeep.',
};
